id: P009229
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:03.911244
source_metadata:
  id: bdr:W23611
  title: ལམ་ཟབ་ལེའུ་བདུན་མ
  author: ''
  volumes:
    29e3aaf1c0834257b3f89308a1dd905a:
      image_group_id: I2287
      title: ''
      volume_number: 1
      total_pages: 44
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
