id: IBCE1B1CF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:47:31+00:00'
last_modified: '2022-06-08T09:32:07.317953+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23611
  title: ལམ་ཟབ་ལེའུ་བདུན་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A0C6:
      image_group_id: I2287
      title: ''
      total_pages: 44
      order: 1
      base_file: A0C6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
